/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SP
 */
public class ProyectoMatrices2 extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoMatrices2
     */
    public ProyectoMatrices2() {
        initComponents();

        JButton botonesHabilitar[] = {cmdCrear, cmdBorrar};
        JButton botonesDeshabilitar[] = {cmdManual, cmdAuto, cmdOperacion};

        Helper.habilitarBotones(botonesHabilitar);
        Helper.deshabilitarBotones(botonesDeshabilitar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFilas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtColumnas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAuto = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdOperacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();
        cmbLetras = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbFiguras = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLetras = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFiguras = new javax.swing.JTable();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Aparajita", 2, 24)); // NOI18N
        jLabel1.setText("Proyecto Matrices ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 170, 20));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Iniciales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 255));
        jLabel2.setText("Filas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 40, -1));

        txtFilas.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        txtFilas.setForeground(new java.awt.Color(0, 153, 102));
        txtFilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilasKeyTyped(evt);
            }
        });
        jPanel2.add(txtFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Columnas");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));

        txtColumnas.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        txtColumnas.setForeground(new java.awt.Color(102, 0, 153));
        txtColumnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColumnasKeyTyped(evt);
            }
        });
        jPanel2.add(txtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 280, 110));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones Matriz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 14), new java.awt.Color(255, 102, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        cmdCrear.setForeground(new java.awt.Color(255, 51, 51));
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 40));

        cmdManual.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        cmdManual.setForeground(new java.awt.Color(255, 0, 0));
        cmdManual.setText("Manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 40));

        cmdAuto.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        cmdAuto.setText("Auto");
        cmdAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 19, 70, 40));

        cmdSalir.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        cmdSalir.setForeground(new java.awt.Color(102, 0, 102));
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 60, 40));

        cmdBorrar.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        cmdBorrar.setForeground(new java.awt.Color(0, 51, 51));
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 80, 40));

        cmdOperacion.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        cmdOperacion.setForeground(new java.awt.Color(255, 102, 0));
        cmdOperacion.setText("Operacion");
        cmdOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperacionActionPerformed(evt);
            }
        });
        jPanel3.add(cmdOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 127, 280, 130));

        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTablaInicial.setEnabled(false);
        jScrollPane1.setViewportView(tblTablaInicial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 700, 240));

        cmbLetras.setFont(new java.awt.Font("Tunga", 2, 18)); // NOI18N
        cmbLetras.setForeground(new java.awt.Color(0, 102, 255));
        cmbLetras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B ", "K ", "M", "W", "Q ", "J ", "G ", "R" }));
        jPanel1.add(cmbLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setText("Ejercicios del 1 al 8");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 150, -1));

        cmbFiguras.setFont(new java.awt.Font("Tunga", 2, 18)); // NOI18N
        cmbFiguras.setForeground(new java.awt.Color(255, 153, 0));
        cmbFiguras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reloj Numerico ", "Reloj Numerico Inverso", "Cruz ", "Rombo" }));
        jPanel1.add(cmbFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 190, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Ejercicios del 9 al 12");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, 160, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tablas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 2, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLetras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblLetras.setEnabled(false);
        jScrollPane2.setViewportView(tblLetras);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 250));

        tblFiguras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblFiguras.setEnabled(false);
        jScrollPane3.setViewportView(tblFiguras);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 620, 250));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1160, 280));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ComputerDesktopWallpapersCollection540_047_inxQEjv.jpg"))); // NOI18N
        lblImagen.setText("jLabel6");
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int numfilas, numcolumnas;

        DefaultTableModel tm, tm2, tm3;

        numfilas = Integer.parseInt(txtFilas.getText());
        numcolumnas = Integer.parseInt(txtColumnas.getText());

        tm = (DefaultTableModel) tblTablaInicial.getModel();
        tm2 = (DefaultTableModel) tblLetras.getModel();
        tm3 = (DefaultTableModel) tblFiguras.getModel();

        tm.setRowCount(numfilas);
        tm.setColumnCount(numcolumnas);

        tm2.setRowCount(numfilas);
        tm2.setColumnCount(numcolumnas);

        tm3.setRowCount(numfilas);
        tm3.setColumnCount(numcolumnas);

        JButton botonesHabilitar[] = {cmdManual, cmdAuto, cmdBorrar};
        JButton botonesDeshabilitar[] = {cmdCrear, cmdOperacion};

        Helper.habilitarBotones(botonesHabilitar);
        Helper.deshabilitarBotones(botonesDeshabilitar);
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        int numfilas, numcolumnas;
        int n;
        int sw, res;

        numcolumnas = tblTablaInicial.getColumnCount();
        numfilas = tblTablaInicial.getRowCount();

        for (int i = 0; i < numfilas; i++) {
            for (int j = 0; j < numcolumnas; j++) {
                do {
                    sw = 1;
                    try {
                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elemento en la posición [" + i + "]" + "[" + j + "]").trim());
                        tblTablaInicial.setValueAt(n, i, j);
                    } catch (NumberFormatException e) {
                        Helper.mensaje(this, "Digite un número válido", 2);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            sw = 1;
                            i = numfilas;
                            j = numcolumnas;

                            Helper.porDefectoTabla(tblTablaInicial);
                            Helper.porDefectoTabla(tblLetras);
                            Helper.porDefectoTabla(tblFiguras);
                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }
        JButton botonesHabilitar[] = {cmdOperacion, cmdBorrar};
        JButton botonesDesabilitar[] = {cmdCrear, cmdManual, cmdAuto};

        Helper.habilitarBotones(botonesHabilitar);
        Helper.deshabilitarBotones(botonesDesabilitar);
    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutoActionPerformed
        int numfilas, numcolumnas, n;

        numcolumnas = tblTablaInicial.getColumnCount();
        numfilas = tblTablaInicial.getRowCount();

        for (int i = 0; i < numfilas; i++) {
            for (int j = 0; j < numcolumnas; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
            }
        }
        JButton botonesHabilitar[] = {cmdOperacion, cmdBorrar};
        JButton botonesDesabilitar[] = {cmdCrear, cmdAuto, cmdManual};

        Helper.habilitarBotones(botonesHabilitar);
        Helper.deshabilitarBotones(botonesDesabilitar);
    }//GEN-LAST:event_cmdAutoActionPerformed

    private void cmdOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperacionActionPerformed
        int numfilas, numcolumnas, letras, figuras;

        numfilas = Integer.parseInt(txtFilas.getText());
        numcolumnas = Integer.parseInt(txtColumnas.getText());
        letras = cmbLetras.getSelectedIndex();
        figuras = cmbFiguras.getSelectedIndex();
        Helper.limpiadoTabla(tblLetras);
        Helper.limpiadoTabla(tblFiguras);

        switch (letras) {
            case 0:
                Helper.letraB(tblTablaInicial, tblLetras);
                break;
            case 1:
                Helper.letraK(tblTablaInicial, tblLetras);
                break;
            case 2:
                Helper.letraM(tblTablaInicial, tblLetras);
                break;
            case 3:
                Helper.letraW(tblTablaInicial, tblLetras);
                break;
            case 4:
                Helper.letraQ(tblTablaInicial, tblLetras);
                break;
            case 5:
                Helper.letraJ(tblTablaInicial, tblLetras);
                break;
            case 6:
                Helper.letraG(tblTablaInicial, tblLetras);
                break;
            case 7:
                Helper.letraR(tblTablaInicial, tblLetras);
                break;
        }
        switch (figuras) {
            case 0:
                Helper.relojNumerico(tblTablaInicial, tblFiguras);
                break;
            case 1:
                Helper.relojNumericoInverso(tblTablaInicial, tblFiguras);
                break;
            case 2:
                Helper.Cruz(tblTablaInicial, tblFiguras);
                break;
            case 3:
                Helper.Rombo(tblTablaInicial, tblFiguras);
                break;
        }

        JButton botonesHabilitar[] = {cmdOperacion, cmdBorrar};
        JButton botonesDeshabilitar[] = {cmdAuto, cmdManual};

    }//GEN-LAST:event_cmdOperacionActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       int numcolumnas, numfilas;

        numcolumnas = tblTablaInicial.getColumnCount();
        numfilas = tblTablaInicial.getRowCount();
        DefaultTableModel tm, tm2,tm3;
        txtFilas.setText("");
        txtColumnas.setText("");
        txtFilas.requestFocusInWindow();
        cmbLetras.setSelectedIndex(0); 
        cmbFiguras.setSelectedIndex(0);

        Helper.porDefectoTabla(tblTablaInicial);
        Helper.porDefectoTabla(tblLetras); 
        Helper.porDefectoTabla(tblFiguras);

        JButton botonesHabilitar[] = {cmdCrear, cmdBorrar};
        JButton botonesDeshabilitar[] = {cmdAuto, cmdManual, cmdOperacion};

        Helper.habilitarBotones(botonesHabilitar);
        Helper.deshabilitarBotones(botonesDeshabilitar);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void txtFilasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilasKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) || !Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtFilasKeyTyped

    private void txtColumnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColumnasKeyTyped
       char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) || !Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtColumnasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoMatrices2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoMatrices2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoMatrices2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoMatrices2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoMatrices2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbFiguras;
    private javax.swing.JComboBox cmbLetras;
    private javax.swing.JButton cmdAuto;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdOperacion;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTable tblFiguras;
    private javax.swing.JTable tblLetras;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JTextField txtColumnas;
    private javax.swing.JTextField txtFilas;
    // End of variables declaration//GEN-END:variables
}
